const CONTENT_TYPES = {
    VIDEO: "VIDEO",
    CHANNEL: "CHANNEL",
    GOD: "GOD",
    GENERIC: "GENERIC"
}

const CARD_TYPES = {
    LARGE_RECTANGLE: "LARGE_RECTANGLE",
    MEDIUM_SQUARE: "MEDIUM_SQUARE",
    LARGE_SQUARE: "LARGE_SQUARE",
    SMALL_SQUARE: "SMALL_SQUARE",
    HORIZONTAL_RECTANGLE: "HORIZONTAL_RECTANGLE",
    MEDIUM_RECTANGLE: "MEDIUM_RECTANGLE",
    VERTICAL_RECTANGLE: "VERTICAL_RECTANGLE",
    CIRCLE: "CIRCLE",
    SMALL_RECTANGLE: "SMALL_RECTANGLE"
}

const LAYOUT_TYPES = {
    SLIDER: "SLIDER",
    HORIZONTAL_SCROLL: "HORIZONTAL_SCROLL",
    THREE_COLUMN_LAYOUT: "THREE_COLUMN_LAYOUT",
    TWO_COLUMN_LAYOUT: "TWO_COLUMN_LAYOUT",
    HEADER: 'HEADER'
}

module.exports = {
    CONTENT_TYPES, CARD_TYPES, LAYOUT_TYPES
}